[build]
  publish = "docs"
  command = ""

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/README"
  to = "/"
  status = 301

[[redirects]]
  from = "/release"
  to = "/releases/"
  status = 301

[[redirects]]
  from = "/releases"
  to = "/releases/"
  status = 301

[[redirects]]
  from = "/security"
  to = "/security/"
  status = 301

[[redirects]]
  from = "/quickstart"
  to = "/quickstart/"
  status = 301

[[redirects]]
  from = "/api"
  to = "/api/"
  status = 301

[[redirects]]
  from = "/auth-methods"
  to = "/auth-methods/"
  status = 301

[[redirects]]
  from = "/contributing"
  to = "/contributing/"
  status = 301
